spring:
  application:
    name: Payment-Service

  datasource:
    url: jdbc:mysql://localhost:3306/PaymentDB
    username: root
    password: Root1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 5551

razorpay:
  api:
    key: ""
    secret: ""

stripe:
  api:
    key: ""
    secret: ""


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8081/eureka/"