spring:
  application:
    name: user-microservice

  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: Root1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 5554

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8081/eureka/"
